/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;
import produtos.Produto;
import dao.ProdutoDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel
 */
public class CadastroProduto extends javax.swing.JFrame {

    /**
     * Creates new form JFrameCadastro
     */

    private Produto objetoProduto;
    

    public CadastroProduto() {
        initComponents();
        this.objetoProduto = new Produto();
    }
    String user = "root";
    String password = "admin";
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nome = new javax.swing.JLabel();
        TextNome = new javax.swing.JTextField();
        Preco = new javax.swing.JLabel();
        Estoque = new javax.swing.JLabel();
        Minimo = new javax.swing.JLabel();
        Maximo = new javax.swing.JLabel();
        Unidade = new javax.swing.JLabel();
        Categoria = new javax.swing.JLabel();
        TextPreco = new javax.swing.JFormattedTextField();
        TextEstoque = new javax.swing.JTextField();
        TextMinimo = new javax.swing.JTextField();
        TextMaximo = new javax.swing.JTextField();
        TextCategoria = new javax.swing.JComboBox<>();
        Cancelar = new javax.swing.JButton();
        Limpar = new javax.swing.JButton();
        Aviso = new javax.swing.JLabel();
        Salvar = new javax.swing.JButton();
        TextUnidade = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produtos");
        setResizable(false);

        Nome.setText("Nome do Produto:");

        TextNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNomeActionPerformed(evt);
            }
        });

        Preco.setText("Preço Unitário");

        Estoque.setText("Quantidade Estoque");

        Minimo.setText("Quantidade Mínima");

        Maximo.setText("Quantidade Máxima");

        Unidade.setText("Unidade");

        Categoria.setText("Categoria");

        TextCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "\"Selecione...\"", "Item 1", "Item 2" }));

        Cancelar.setText("Cancelar");

        Limpar.setText("Limpar");

        Aviso.setText("Aviso");

        Salvar.setText("Salvar");
        Salvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalvarMouseClicked(evt);
            }
        });
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Aviso)
                .addGap(262, 262, 262))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Preco)
                            .addComponent(Unidade)
                            .addComponent(Nome)
                            .addComponent(Estoque)
                            .addComponent(Minimo)
                            .addComponent(Maximo)
                            .addComponent(Categoria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(159, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Limpar)
                        .addGap(152, 152, 152)
                        .addComponent(Cancelar)
                        .addGap(6, 6, 6))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {TextCategoria, TextPreco});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Preco)
                    .addComponent(TextPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Unidade)
                    .addComponent(TextUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Estoque)
                    .addComponent(TextEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Minimo)
                    .addComponent(TextMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Maximo)
                    .addComponent(TextMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Categoria)
                    .addComponent(TextCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Aviso)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancelar)
                    .addComponent(Limpar)
                    .addComponent(Salvar))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNomeActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SalvarActionPerformed

    private void SalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvarMouseClicked
         
            // recebendo e validando dados da interface gráfica.
            /*
            String Nome = "";
            double Preco = 0;
            String Unidade = "";
            int Quantidade_estoque = 0;
            int Estoque_minimo = 0;
            int Estoque_maximo = 0;
            */
           try {
            int Id = this.objetoProduto.maiorID() + 1;
            String Nome = this.TextNome.getText();
            double Preco = Double.parseDouble(this.TextPreco.getText());
            String Unidade = this.TextUnidade.getText();
            int Quantidade_estoque = Integer.parseInt(this.TextEstoque.getText());
            int Estoque_minimo = Integer.parseInt(this.TextMinimo.getText());
            int Estoque_maximo = Integer.parseInt(this.TextMaximo.getText());
            int id_categoria = 0; // ajustar conforme lógica real
            String Nome_categoria = this.TextCategoria.getText();
            String Tamanho = this.TextTamanho.getText();
           String Embalagem = this.TextEmbalagem.getText();

            Produto novoProduto = new Produto(
                Id,
                Nome,
                Preco,
                Unidade,
                Quantidade_estoque,
                Estoque_minimo,
                Estoque_maximo,
                id_categoria,
                Nome_categoria,
                Tamanho,
                Embalagem,
                user,
                password);
            

            if (this.objetoProduto.insertProdutoBD(Id,
                Nome,
                Preco,
                Unidade,
                Quantidade_estoque,
                Estoque_minimo,
                Estoque_maximo,
                id_categoria,
                Nome_categoria,
                Tamanho,
                Embalagem,
                user,
                password)) {
                JOptionPane.showMessageDialog(null, "Produto Cadastrado com Sucesso!");
                // Limpa os campos da interface
                this.TextNome.setText("");
                this.TextPreco.setText("");
                this.TextUnidade.setText("");
                this.TextEstoque.setText("");
                this.TextMinimo.setText("");
                this.TextMaximo.setText("");
                //this.TextCategoria.setText("");
               // this.TextTamanho.setText("");
               // this.TextEmbalagem.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar produto.");
            }

            System.out.println(this.objetoProduto.getMinhaLista().toString());

        } catch (NumberFormatException erro2) {
            JOptionPane.showMessageDialog(null, "Informe um número válido.");
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro: " + erro.getMessage());
        }

    // TODO add your handling code here:
    }//GEN-LAST:event_SalvarMouseClicked
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aviso;
    private javax.swing.JButton Cancelar;
    private javax.swing.JLabel Categoria;
    private javax.swing.JLabel Estoque;
    private javax.swing.JButton Limpar;
    private javax.swing.JLabel Maximo;
    private javax.swing.JLabel Minimo;
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel Preco;
    private javax.swing.JButton Salvar;
    private javax.swing.JComboBox<String> TextCategoria;
    private javax.swing.JTextField TextEstoque;
    private javax.swing.JTextField TextMaximo;
    private javax.swing.JTextField TextMinimo;
    private javax.swing.JTextField TextNome;
    private javax.swing.JFormattedTextField TextPreco;
    private javax.swing.JFormattedTextField TextUnidade;
    private javax.swing.JLabel Unidade;
    // End of variables declaration//GEN-END:variables
}
