package visao;
import javax.swing.JOptionPane;

public class Master extends javax.swing.JFrame {

    private String user;
    private String password;

    public Master() {
        initComponents();
        fazerLogin();
    }

    
    private void fazerLogin() {
        user = JOptionPane.showInputDialog(this, "Digite o nome de usuário do banco de dados:", "Login", JOptionPane.QUESTION_MESSAGE);
        password = JOptionPane.showInputDialog(this, "Digite a senha do banco de dados:", "Login", JOptionPane.QUESTION_MESSAGE);

        if (user == null || password == null || user.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Usuário e senha são obrigatórios.", "Erro", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuBar = new javax.swing.JMenuBar();
        MenuCadastro = new javax.swing.JMenu();
        CadastroProduto = new javax.swing.JMenuItem();
        CadastroCategoria = new javax.swing.JMenuItem();
        MenuConsultaEdicao = new javax.swing.JMenu();
        ConsultaProduto = new javax.swing.JMenuItem();
        ConsultaCategoria = new javax.swing.JMenuItem();
        MenuMovimentar = new javax.swing.JMenu();
        Movimentar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setResizable(false);

        MenuCadastro.setText("Cadastro");

        CadastroProduto.setText("Cadastro de Produtos");
        CadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroProdutoActionPerformed(evt);
            }
        });
        MenuCadastro.add(CadastroProduto);

        CadastroCategoria.setText("Cadastro de Categorias");
        CadastroCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroCategoriaActionPerformed(evt);
            }
        });
        MenuCadastro.add(CadastroCategoria);

        MenuBar.add(MenuCadastro);

        MenuConsultaEdicao.setText("Consulta/Edição");

        ConsultaProduto.setText("Consulta de Produtos");
        ConsultaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaProdutoActionPerformed(evt);
            }
        });
        MenuConsultaEdicao.add(ConsultaProduto);

        ConsultaCategoria.setText("Consulta de Categorias");
        ConsultaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaCategoriaActionPerformed(evt);
            }
        });
        MenuConsultaEdicao.add(ConsultaCategoria);

        MenuBar.add(MenuConsultaEdicao);

        MenuMovimentar.setText("Movimentação");

        Movimentar.setText("Movimentação");
        Movimentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovimentarActionPerformed(evt);
            }
        });
        MenuMovimentar.add(Movimentar);

        MenuBar.add(MenuMovimentar);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroProdutoActionPerformed
        CadastroProduto objeto = new CadastroProduto(user, password);
        objeto.setVisible(true);
    }//GEN-LAST:event_CadastroProdutoActionPerformed

    private void CadastroCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroCategoriaActionPerformed
        CadastroCategoria objeto = new CadastroCategoria(user, password);
        objeto.setVisible(true);
    }//GEN-LAST:event_CadastroCategoriaActionPerformed

    private void ConsultaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaProdutoActionPerformed
        ConsultaProduto objeto = new ConsultaProduto(user, password);
        objeto.setVisible(true);
    }//GEN-LAST:event_ConsultaProdutoActionPerformed

    private void ConsultaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaCategoriaActionPerformed
        ConsultaCategoria objeto = new ConsultaCategoria(user, password);
        objeto.setVisible(true);
    }//GEN-LAST:event_ConsultaCategoriaActionPerformed

    private void MovimentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovimentarActionPerformed
        MovimentacaoVisao objeto = new MovimentacaoVisao (user, password);
        objeto.setVisible(true);
    }//GEN-LAST:event_MovimentarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Master().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadastroCategoria;
    private javax.swing.JMenuItem CadastroProduto;
    private javax.swing.JMenuItem ConsultaCategoria;
    private javax.swing.JMenuItem ConsultaProduto;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenu MenuConsultaEdicao;
    private javax.swing.JMenu MenuMovimentar;
    private javax.swing.JMenuItem Movimentar;
    // End of variables declaration//GEN-END:variables
}
